version: '3.8'

services:
  app:
    container_name: website
    # image: chiragjaniotocapital/webapp:latest
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - '3000'
    environment:
      - NODE_ENV
      - NEXT_PUBLIC_BASE_API_URL
  nginx:
    container_name: webserver
    # image: chiragjaniotocapital/webapp:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    expose:
      - '80'
    ports:
      - '80:80'
    environment:
      - NODE_ENV
      - NEXT_PUBLIC_BASE_API_URL
